version: '3.8'

services:
  jira-mcp-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JIRA_URL=${JIRA_URL}
      - JIRA_USER_EMAIL=${JIRA_USER_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
    env_file:
      - .env