name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Check Formatting
      working-directory: ./jira-mcp-server
      run: |
        make fmt
        git diff --exit-code

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run Linter
      working-directory: ./jira-mcp-server
      run: make lint

    - name: Run Unit Tests
      working-directory: ./jira-mcp-server
      run: make test

    - name: Run Integration Tests
      working-directory: ./jira-mcp-server
      run: make test-integration

    - name: Build Binary
      working-directory: ./jira-mcp-server
      run: make build

    - name: Build Docker Image
      working-directory: ./jira-mcp-server
      run: make docker-build